language: java
jdk:
  - openjdk13
os: 
  - linux
dist:
  - debian
addons:
  sonarcloud:
    organization: "danilo-dellorco"
    token: "64bea92fca0e686e303d4c6327859d0fe075cd85"
script: 
  - mvn clean verify -Psonar